{:user {:plugins [[lein-difftest "1.3.8"]
                  [lein-marginalia "0.7.1"]
                  [lein-pprint "1.1.1"]
                 ;; [lein-swank "1.4.4"]
                  [org.clojure/tools.nrepl "0.2.0-beta10"]
                  [compojure/lein-template "0.2.0"]
                  [lein-newnew "0.2.6"]
                  [lein-midje "1.0.10"]
                  [lein-create-template "0.1.1"]
                  [lein-tarsier "0.9.4"]]
        } }
